// File generated by tool/setup_firebase.dart
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static bool get isConfigured => true;

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return windows;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return windows;
      case TargetPlatform.macOS:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions no están configuradas para esta plataforma.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPYEQpwn2wrxg0u4Vv7BvojQGnV7a2epE',
    appId: '1:813722460139:android:f159a807318cd2f964c3ae',
    messagingSenderId: '813722460139',
    projectId: 'stock-negocio-maco',
    storageBucket: 'stock-negocio-maco.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiWiF-_6rPVhjdDU_Sewg9wUiz7KJOctk',
    appId: '1:813722460139:web:616f52f8300bce7e64c3ae',
    messagingSenderId: '813722460139',
    projectId: 'stock-negocio-maco',
    authDomain: 'stock-negocio-maco.firebaseapp.com',
    storageBucket: 'stock-negocio-maco.firebasestorage.app',
  );
}
